
name: Junit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

 

      # Runs a single command using the runners shell
      - name: JDK and JRE
        run: |
             sudo apt install default-jdk
             sudo apt install default-jre

 

      # Runs a set of commands using the runners shell
      - name: Verify version
        run: java -version
      - name: Compile
        run: |
          cd Implementation/
          javac ATM.java MenuOption.class UserAccount.java
